CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100) NULL,
  last_name VARCHAR(100) NULL,
  suffix VARCHAR(30) NULL,
  sex VARCHAR(20) NULL,
  email VARCHAR(191) NOT NULL,
  contact_number VARCHAR(30) NULL,
  address VARCHAR(255) NULL,
  barangay VARCHAR(100) NULL,
  municipality_city VARCHAR(100) NULL,
  province VARCHAR(100) NULL,
  region VARCHAR(100) NULL,
  username VARCHAR(100) NULL,
  password_hash VARCHAR(255) NOT NULL,
  roles JSON NULL,
  position VARCHAR(150) NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'active',
  profile_picture VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY users_email_unique (email),
  UNIQUE KEY users_username_unique (username),
  KEY idx_users_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO users (
  id,
  name,
  first_name,
  middle_name,
  last_name,
  suffix,
  sex,
  email,
  contact_number,
  address,
  barangay,
  municipality_city,
  province,
  region,
  username,
  password_hash,
  roles,
  position,
  status,
  profile_picture,
  created_at,
  updated_at,
  deleted_at
) VALUES
  (
    1,
    'Mark Emil Dacoylo',
    'Mark',
    'Emil',
    'Dacoylo',
    '',
    'male',
    'mark@example.com',
    '09171234567',
    'Purok 1, San Isidro',
    'San Isidro',
    'Talisay City',
    'Cebu',
    'Region VII',
    'mark.dacoylo',
    '$2b$10$rPoRFgXqoi/EnRUYe2eWUexr55iFQl3MB3Q956jdcYW1.QmfwlZai',
    JSON_ARRAY('admin', 'developer'),
    'System Administrator',
    'active',
    'https://randomuser.me/api/portraits/men/1.jpg',
    '2026-01-10 08:30:00',
    '2026-01-10 08:30:00',
    NULL
  ),
  (
    2,
    'Juan Dela Cruz',
    'Juan',
    '',
    'Dela Cruz',
    '',
    'male',
    'juan@example.com',
    '09171234568',
    'Blk 4 Lot 9 Riverside',
    'Poblacion',
    'Naga City',
    'Cebu',
    'Region VII',
    'juan.cruz',
    '$2b$10$rPoRFgXqoi/EnRUYe2eWUexr55iFQl3MB3Q956jdcYW1.QmfwlZai',
    JSON_ARRAY('user'),
    'Teacher I',
    'active',
    'https://randomuser.me/api/portraits/men/2.jpg',
    '2026-01-12 10:15:00',
    '2026-01-12 10:15:00',
    NULL
  ),
  (
    3,
    'Maria Santos',
    'Maria',
    '',
    'Santos',
    '',
    'female',
    'maria@example.com',
    '09171234569',
    'Sitio Proper',
    'Mabolo',
    'Cebu City',
    'Cebu',
    'Region VII',
    'maria.santos',
    '$2b$10$rPoRFgXqoi/EnRUYe2eWUexr55iFQl3MB3Q956jdcYW1.QmfwlZai',
    JSON_ARRAY('user'),
    'Teacher II',
    'inactive',
    'https://randomuser.me/api/portraits/women/1.jpg',
    '2026-02-01 14:45:00',
    '2026-02-01 14:45:00',
    NULL
  );

SELECT
  id,
  name,
  first_name,
  middle_name,
  last_name,
  suffix,
  sex,
  email,
  contact_number,
  address,
  barangay,
  municipality_city,
  province,
  region,
  username,
  roles,
  position,
  status,
  profile_picture,
  created_at,
  updated_at,
  deleted_at
FROM users
WHERE deleted_at IS NULL
ORDER BY id DESC;

UPDATE users
SET deleted_at = NOW(),
    status = 'inactive'
WHERE id = 3
  AND deleted_at IS NULL;

UPDATE users
SET deleted_at = NULL,
    status = 'active'
WHERE id = 3;
